import { CompanyDataProps } from "@/types/company";

export const mockData: CompanyDataProps = {
  id: "abc123",
  displayName: "Coffee Club Berlin",
  formattedAddress: "Alexanderplatz 1, 10178 Berlin, Germany",
  googleMapsUri: "https://maps.google.com/?q=Coffee+Club+Berlin",
  internationalPhoneNumber: "+49 30 123456",
  websiteUri: "https://coffeeclub.de",
  rating: 4.5,
  userRatingCount: 230,
  businessStatus: "OPERATIONAL",
  location: { latitude: 52.521918, longitude: 13.413215 },
  viewport: {},
  plusCode: "9F4M+5C Berlin",
  types: ["cafe", "food", "point_of_interest", "establishment"],
  addressComponents: [],
  regularOpeningHours: {},
  currentOpeningHours: {},
  secondaryOpeningHours: {},
  specialDays: [],
  utcOffsetMinutes: 120,
  photos: ["/images/coffee.jpg", "/images/interior.jpg"],
  reviews: [],
  priceLevel: 2,
  accessibilityOptions: {},
  editorialSummary: { text: "A cozy coffee shop located in the heart of Berlin." },
  takeout: true,
  delivery: true,
  dineIn: true,
  servesBeer: false,
  servesBreakfast: true,
  servesBrunch: false,
  servesDinner: true,
  servesLunch: true,
  servesVegetarianFood: true,
  servesWine: false,
  reservable: true,
  goodForChildren: true,
  paymentOptions: {},
  parkingOptions: {},
  businessName: "Coffee Club GmbH",
  businessContact: {}
};