export enum SortOptions {
  RATING = 'rating',
  RATING_COUNT = 'rating count',
  NAME = 'display name',
}

export enum PlacesFields {
  UNSELECTED = "",
  ID = 'places.id',
  DISPLAY_NAME = 'places.displayName',
  FORMATTED_ADDRESS = 'places.formattedAddress',
  GOOGLE_MAPS_URI = 'places.googleMapsUri',
  INTERNATIONAL_PHONE_NUMBER = 'places.internationalPhoneNumber',
  WEBSITE_URI = 'places.websiteUri',
  RATING = 'places.rating',
  USER_RATING_COUNT = 'places.userRatingCount',
  BUSINESS_STATUS = 'places.businessStatus',
  LOCATION = 'places.location',
  VIEWPORT = 'places.viewport',
  PLUS_CODE = 'places.plusCode',
  TYPES = 'places.types',
  ADDRESS_COMPONENTS = 'places.addressComponents',
  REGULAR_OPENING_HOURS = 'places.regularOpeningHours',
  CURRENT_OPENING_HOURS = 'places.currentOpeningHours',
  SECONDARY_OPENING_HOURS = 'places.secondaryOpeningHours',
  SPECIAL_DAYS = 'places.specialDays',
  UTC_OFFSET_MINUTES = 'places.utcOffsetMinutes',
  PHOTOS = 'places.photos',
  REVIEWS = 'places.reviews',
  PRICE_LEVEL = 'places.priceLevel',
  ACCESSIBILITY_OPTIONS = 'places.accessibilityOptions',
  EDITORIAL_SUMMARY = 'places.editorialSummary',
  TAKEOUT = 'places.takeout',
  DELIVERY = 'places.delivery',
  DINE_IN = 'places.dineIn',
  SERVES_BEER = 'places.servesBeer',
  SERVES_BREAKFAST = 'places.servesBreakfast',
  SERVES_BRUNCH = 'places.servesBrunch',
  SERVES_DINNER = 'places.servesDinner',
  SERVES_LUNCH = 'places.servesLunch',
  SERVES_VEGETARIAN_FOOD = 'places.servesVegetarianFood',
  SERVES_WINE = 'places.servesWine',
  RESERVABLE = 'places.reservable',
  GOOD_FOR_CHILDREN = 'places.goodForChildren',
  PAYMENT_OPTIONS = 'places.paymentOptions',
  PARKING_OPTIONS = 'places.parkingOptions',
  BUSINESS_NAME = 'places.businessName',
  BUSINESS_CONTACT = 'places.businessContact',
}

export enum PlaceFields {
  // Essentials (IDs Only)
  Attributions = 'attributions',
  Id = 'id',
  Name = 'name',
  Photos = 'photos',

  // Essentials
  AddressComponents = 'addressComponents',
  AddressDescriptor = 'addressDescriptor',
  AdrFormatAddress = 'adrFormatAddress',
  FormattedAddress = 'formattedAddress',
  Location = 'location',
  PlusCode = 'plusCode',
  PostalAddress = 'postalAddress',
  ShortFormattedAddress = 'shortFormattedAddress',
  Types = 'types',
  Viewport = 'viewport',

  // Pro
  AccessibilityOptions = 'accessibilityOptions',
  BusinessStatus = 'businessStatus',
  ContainingPlaces = 'containingPlaces',
  DisplayName = 'displayName',
  GoogleMapsLinks = 'googleMapsLinks',
  GoogleMapsUri = 'googleMapsUri',
  IconBackgroundColor = 'iconBackgroundColor',
  IconMaskBaseUri = 'iconMaskBaseUri',
  PrimaryType = 'primaryType',
  PrimaryTypeDisplayName = 'primaryTypeDisplayName',
  PureServiceAreaBusiness = 'pureServiceAreaBusiness',
  SubDestinations = 'subDestinations',
  UtcOffsetMinutes = 'utcOffsetMinutes',

  // Enterprise
  CurrentOpeningHours = 'currentOpeningHours',
  CurrentSecondaryOpeningHours = 'currentSecondaryOpeningHours',
  InternationalPhoneNumber = 'internationalPhoneNumber',
  NationalPhoneNumber = 'nationalPhoneNumber',
  PriceLevel = 'priceLevel',
  PriceRange = 'priceRange',
  Rating = 'rating',
  RegularOpeningHours = 'regularOpeningHours',
  RegularSecondaryOpeningHours = 'regularSecondaryOpeningHours',
  UserRatingCount = 'userRatingCount',
  WebsiteUri = 'websiteUri',
}
