import { PlacesFields } from "@/types/google.types";

export const PlaceFieldLabels: Record<PlacesFields, string> = {
  [PlacesFields.UNSELECTED]: "-- select field --",
  [PlacesFields.ID]: "ID",
  [PlacesFields.DISPLAY_NAME]: "Display Name",
  [PlacesFields.FORMATTED_ADDRESS]: "Formatted Address",
  [PlacesFields.GOOGLE_MAPS_URI]: "Google Maps URL",
  [PlacesFields.INTERNATIONAL_PHONE_NUMBER]: "Phone Number",
  [PlacesFields.WEBSITE_URI]: "Website",
  [PlacesFields.RATING]: "Rating",
  [PlacesFields.USER_RATING_COUNT]: "User Rating Count",
  [PlacesFields.BUSINESS_STATUS]: "Business Status",
  [PlacesFields.LOCATION]: "Location",
  [PlacesFields.VIEWPORT]: "Viewport",
  [PlacesFields.PLUS_CODE]: "Plus Code",
  [PlacesFields.TYPES]: "Types",
  [PlacesFields.ADDRESS_COMPONENTS]: "Address Components",
  [PlacesFields.REGULAR_OPENING_HOURS]: "Regular Opening Hours",
  [PlacesFields.CURRENT_OPENING_HOURS]: "Current Opening Hours",
  [PlacesFields.SECONDARY_OPENING_HOURS]: "Secondary Opening Hours",
  [PlacesFields.SPECIAL_DAYS]: "Special Days",
  [PlacesFields.UTC_OFFSET_MINUTES]: "UTC Offset (minutes)",
  [PlacesFields.PHOTOS]: "Photos",
  [PlacesFields.REVIEWS]: "Reviews",
  [PlacesFields.PRICE_LEVEL]: "Price Level",
  [PlacesFields.ACCESSIBILITY_OPTIONS]: "Accessibility Options",
  [PlacesFields.EDITORIAL_SUMMARY]: "Editorial Summary",
  [PlacesFields.TAKEOUT]: "Takeout",
  [PlacesFields.DELIVERY]: "Delivery",
  [PlacesFields.DINE_IN]: "Dine-In",
  [PlacesFields.SERVES_BEER]: "Serves Beer",
  [PlacesFields.SERVES_BREAKFAST]: "Serves Breakfast",
  [PlacesFields.SERVES_BRUNCH]: "Serves Brunch",
  [PlacesFields.SERVES_DINNER]: "Serves Dinner",
  [PlacesFields.SERVES_LUNCH]: "Serves Lunch",
  [PlacesFields.SERVES_VEGETARIAN_FOOD]: "Serves Vegetarian Food",
  [PlacesFields.SERVES_WINE]: "Serves Wine",
  [PlacesFields.RESERVABLE]: "Reservable",
  [PlacesFields.GOOD_FOR_CHILDREN]: "Good for Children",
  [PlacesFields.PAYMENT_OPTIONS]: "Payment Options",
  [PlacesFields.PARKING_OPTIONS]: "Parking Options",
  [PlacesFields.BUSINESS_NAME]: "Business Name",
  [PlacesFields.BUSINESS_CONTACT]: "Business Contact",
};
