import { PlaceFields } from "@/types/google";


export const PlaceFieldLabels: Record<PlaceFields, string> = {
  [PlaceFields.UNSELECTED]: "-- select field --",
  [PlaceFields.ID]: "ID",
  [PlaceFields.DISPLAY_NAME]: "Display Name",
  [PlaceFields.FORMATTED_ADDRESS]: "Formatted Address",
  [PlaceFields.GOOGLE_MAPS_URI]: "Google Maps URL",
  [PlaceFields.INTERNATIONAL_PHONE_NUMBER]: "Phone Number",
  [PlaceFields.WEBSITE_URI]: "Website",
  [PlaceFields.RATING]: "Rating",
  [PlaceFields.USER_RATING_COUNT]: "User Rating Count",
  [PlaceFields.BUSINESS_STATUS]: "Business Status",
  [PlaceFields.LOCATION]: "Location",
  [PlaceFields.VIEWPORT]: "Viewport",
  [PlaceFields.PLUS_CODE]: "Plus Code",
  [PlaceFields.TYPES]: "Types",
  [PlaceFields.ADDRESS_COMPONENTS]: "Address Components",
  [PlaceFields.REGULAR_OPENING_HOURS]: "Regular Opening Hours",
  [PlaceFields.CURRENT_OPENING_HOURS]: "Current Opening Hours",
  [PlaceFields.SECONDARY_OPENING_HOURS]: "Secondary Opening Hours",
  [PlaceFields.SPECIAL_DAYS]: "Special Days",
  [PlaceFields.UTC_OFFSET_MINUTES]: "UTC Offset (minutes)",
  [PlaceFields.PHOTOS]: "Photos",
  [PlaceFields.REVIEWS]: "Reviews",
  [PlaceFields.PRICE_LEVEL]: "Price Level",
  [PlaceFields.ACCESSIBILITY_OPTIONS]: "Accessibility Options",
  [PlaceFields.EDITORIAL_SUMMARY]: "Editorial Summary",
  [PlaceFields.TAKEOUT]: "Takeout",
  [PlaceFields.DELIVERY]: "Delivery",
  [PlaceFields.DINE_IN]: "Dine-In",
  [PlaceFields.SERVES_BEER]: "Serves Beer",
  [PlaceFields.SERVES_BREAKFAST]: "Serves Breakfast",
  [PlaceFields.SERVES_BRUNCH]: "Serves Brunch",
  [PlaceFields.SERVES_DINNER]: "Serves Dinner",
  [PlaceFields.SERVES_LUNCH]: "Serves Lunch",
  [PlaceFields.SERVES_VEGETARIAN_FOOD]: "Serves Vegetarian Food",
  [PlaceFields.SERVES_WINE]: "Serves Wine",
  [PlaceFields.RESERVABLE]: "Reservable",
  [PlaceFields.GOOD_FOR_CHILDREN]: "Good for Children",
  [PlaceFields.PAYMENT_OPTIONS]: "Payment Options",
  [PlaceFields.PARKING_OPTIONS]: "Parking Options",
  [PlaceFields.BUSINESS_NAME]: "Business Name",
  [PlaceFields.BUSINESS_CONTACT]: "Business Contact",
};
